export const texts = {
  en: {
    logo: "Blue Sea Catering",
    heroTitle: "Blue Sea Catering",
    heroSubtitle: `In today's Vision for Saudi Arabia, the need for comprehensive, high-quality hospitality services has never been greater. Companies need reliable partners to smoothly and efficiently manage their operations, particularly in catering. Having expertise, commitment, and a forward-thinking approach is crucial in ensuring excellence and satisfaction in every detail.`,
    home: "Home",
    services: "Services",
    projects: "Projects",
        contact: "Contact",
        ourStoryTitle: "Our Story",
    ourStoryDescription: "Blue Sea Catering is a strategic extension of Al Mazroui Catering Group (AMC), expanding its reach into new markets and bringing world-class catering services to Saudi Arabia.",
    ourStoryItems: [
      "Al Mazroui Catering Services Co. LLC – Dubai",
      "Inter Care Catering Services Co. LLC – Dubai",
      "Al Mazroui Catering – Jordan Branch",
      "Hassan Ali Facility Management – KSA",
      "Royal Catering Services – Qatar",
      "Blue Sea Catering – KSA"],
    whoWeAreTitle: "Who We Are",
    whoWeAreDescription: `Blue Sea Catering is a leading provider of catering services in Saudi Arabia, offering customized food solutions for a wide range of industries and special events. Whether it's sites, corporate offices, remote locations, or special events, we ensure the highest standards of food quality, hygiene, and service. With a focus on customer satisfaction, we provide efficient and reliable catering services that meet the diverse needs of clients across the Kingdom.`,
     ourVisionTitle: "Our Vision",
    ourVisionDescription: "To be a leader in Saudi Arabia's catering and facility management industry by providing high-quality, innovative, and sustainable services.",
    ourVisionPoints: [
      "Rigorous self-auditing",
      "Corrective actions",
      "External evaluations",
      "Strict compliance with a formalized Quality Management System",
    ],
    ourVision2030: "In alignment with Vision 2030, we actively contribute to improving quality of life, fostering economic diversification, and developing local talent.",
     coreValuesTitle: "Core Values",
    coreValuesIntro: "It is at the heart of everything we do. We strive to deliver personalized service, maintain open communication, ensure high-quality work, meet deadlines, and continuously improve our offerings. By listening to our clients' feedback and tailoring our services to their specific needs, we have built strong relationships and established a reputation for excellence in the industry.",
    coreValues: [
      {
        title: "Sustainability",
        description: "We prioritize sustainable practices in all our operations.",
      },
      {
        title: "Community Engagement",
        description: "We actively engage with our communities and contribute positively.",
      },
      {
        title: "Adaptability & Collaboration",
        description: "We adapt to change and collaborate closely with clients & stakeholders.",
      },
      {
        title: "Customer Satisfaction",
        description: "We deliver personalized services, maintain open communication, and ensure high-quality work.",
      },
        ],
        servicesTitle: "Our Services",
    servicesDescription: "We offer a wide range of high-quality services tailored to industrial, corporate, and remote environments.",
    servicesData: [
      {
        title: "Industrial Catering",
        description: "We provide high-quality, nutritious meals to teams in isolated and challenging locations, ensuring reliable on-site meal delivery, tailored kitchen setups, and efficient logistics.",
        items: ["Catering Solutions", "Laundry Services", "Housekeeping", "Port Cabin Mobilization"],
      },
      {
        title: "On & Offshore Catering",
        description: "We specialize in providing exceptional catering services for both onshore and offshore oil rigs. Equipped to handle remote and industrial environments, ensuring high-quality.",
        items: ["Senior & Junior Staff Accommodation", "Kitchen/Restaurant Designing & Furnishing"],
      },
      {
        title: "Corporate Catering (Indoor/Outdoor)",
        description: "Customized catering solutions for corporate cafeterias, on-desk meals, buffets, and snack trolleys, helping reduce stress and boost staff productivity.",
        items: ["Corporate Receivals", "Corporate Dinners", "Corporate Buffets", "Conference Buffets"],
      },
      {
        title: "Private Events (Indoor/Outdoor)",
        description: "Refined dining experience, featuring themed menus, live cooking stations, and personalized setups.",
        items: ["Luxury Dining", "Home Dinners", "Weddings", "Picnic / Barbeques"],
      },
      {
        title: "Camp Construction and Management",
        description: "Blue Sea Catering offers prefabricated and permanent camps tailored to your project needs.",
        items: ["Housekeeping, cleaning, recreation, laundry, security, clinic, transport", "12/24 hours operational support"],
      },
      {
        title: "Desert & Remote Location Catering",
        description: "Comprehensive food, accommodation, and support services for isolated regions across Saudi Arabia.",
        items: [],
      },
      {
        title: "Foodstuff Trading",
        description: "Trusted supplier of high-quality food products, sourcing locally and globally, ensuring fresh, safe, and quality items.",
        items: [],
      },
        ],
        whyWeStandOutTitle: "Why We Stand Out?",
    whyWeStandOutDescription: "Our commitment to excellence and innovation sets us apart in the catering industry.",
    whyWeStandOutFeatures: [
      { title: "Specialty Cuisine", description: "Customized menus showcasing the finest global and regional cuisine." },
      { title: "On-Site Preparation", description: "Personalized catering with freshly prepared meals at your location." },
      { title: "Themed Catering", description: "Catering designed to perfectly match corporate or private event themes." },
      { title: "Fast and Reliable Delivery", description: "7/24 availability for timely delivery with a large-scale fleet to meet urgent and ongoing needs." },
      { title: "Quality Control", description: "Consistent excellence from sourcing to delivery." },
      { title: "Waste Management", description: "Segregating, collecting, and responsibly disposing of waste." },
        ],
        healthSafetyTitle: "Health & Safety Commitment",
    healthSafetyDescription: "We are committed to maintaining the highest standards of health and safety in all our operations.",
    healthSafetyPoints: [
      { title: "Food Safety", description: "Proper handling, storage, & preparation to prevent contamination." },
      { title: "Hygiene Practices", description: "Handwashing, PPE use, and clean workspaces." },
      { title: "Supplier Evaluation", description: "Ensuring ingredients meet safety and quality standards." },
      { title: "Temperature Control", description: "Maintained during preparation, storage, and transport." },
      { title: "Regular Audits", description: "Ongoing checks to ensure compliance and improvement." },
      { title: "Training & Certification", description: "Continuous team training on food safety and hygiene." },
      { title: "Emergency Procedures", description: "Clear protocols for addressing health and safety issues." },
        ],
        projectsTitle: "Projects",
    completedProjectsTitle: "Completed Projects",
    runningProjectsTitle: "Running Projects",
    completedProjects: [
      "Aseel Universal Garment - Jordan",
      "AMC-AZDA JV Catering. Dammam-KSA",
      "Metro VFR Limited - Dubai",
      "Salini Construttori - Dubai",
      "Todini Costruzioni Generali - Dubai",
      "Belleli Energy Sr. Dubai - Sharjah",
      "Dubai Polo Club - Dubai",
      "Dubai Precast - Dubai",
      "Sendan Al Emarat - Dubai",
      "Sharjah Airport Free Zone, Sharjah",
      "Sungwon Corporation - Dubai",
      "Arabtec Construction LLC - Dubai",
      "Bhawan Engineering. L.L.C. Dubai",
      "Kele Contracting Co. LLC-Dubai",
      "Dutco Beaty Balfour, Dubai",
      "Meydan Racecourse, Dubai",
      "Transgulf Dubai, UAE & KSA",
      "Al Laith Scaffolding LLC",
      "Green Works LLC, Dubai",
      "Deco Emirates, Dubai",
    ],
    runningProjects: [
      "Elegancia MEP - Red Sea Project",
      "Fast Construction - Red Sea Project",
      "First Fix - Red Sea Project",
      "Elegancia Fit out",
      "Elenco Group",
      "Bk Gulf - Red Sea Project",
      "Al Futtaim Engineering KSA"
    ],
        partnersTitle: "Our Success Partners",
    partnersDescription: "Trusted partners who have contributed to our growth and success across various projects and industries.",
      contactTitle: "Contact Us",
    phone: "0559361915",
    email: "Info@mcatering.com",
    address: "48321, Omar Ibn Abdulaziz St, Umluj, Saudi Arabia",
    ctaTitle: "Are You Ready?",
    ctaDescription: "We’re ready to create a catering solution that’s perfect for you!",
    qrText: "Scan to Contact Us",
    companyName: "Blue Sea Catering",
    rights: "All rights reserved.",
  
    },
  ar: {
    logo: "البحر الأزرق للتموين والإعاشة",
    heroTitle: "البحر الأزرق للتموين والإعاشة",
    heroSubtitle: `في رؤية المملكة العربية السعودية اليوم، لم يكن الطلب على خدمات الضيافة الشاملة وعالية الجودة أكبر من الآن. تحتاج الشركات إلى شركاء موثوقين لإدارة عملياتها بسلاسة وكفاءة، خصوصًا في مجال التموين. إن الخبرة والالتزام والتفكير المستقبلي أمر بالغ الأهمية لضمان التميز والرضا في كل تفصيلة.`,
    home: "الرئيسية",
    services: "الخدمات",
    projects: "المشاريع",
      contact: "اتصل بنا",
        ourStoryTitle: "قصتنا",
    ourStoryDescription: "البحر الأزرق للتموين والإعاشة هو امتداد استراتيجي لمجموعة المزروعي للتموين (AMC)، موسعًا نطاق خدماته إلى أسواق جديدة وتقديم خدمات تموين عالمية المستوى في المملكة العربية السعودية.",
    ourStoryItems: [
      "شركة المزروعي للتموين – دبي",
      "شركة إنتر كير للتموين – دبي",
      "المزروعي للتموين – فرع الأردن",
      "حسن علي لإدارة المرافق – المملكة العربية السعودية",
      "رويال كاترينج سيرفيسز – قطر",
        "البحر الأزرق للتموين والإعاشة – المملكة العربية السعودية",
      
      ],
        whoWeAreTitle: "من نحن",
    whoWeAreDescription: `البحر الأزرق للتموين والإعاشة هو مزود رائد لخدمات التموين في المملكة العربية السعودية، حيث يقدم حلول غذائية مخصصة لمجموعة واسعة من الصناعات والفعاليات الخاصة. سواء كانت مواقع، مكاتب شركات، مواقع نائية، أو فعاليات خاصة، نضمن أعلى معايير جودة الطعام والنظافة والخدمة. مع التركيز على رضا العملاء، نقدم خدمات تموين فعالة وموثوقة تلبي الاحتياجات المتنوعة للعملاء في جميع أنحاء المملكة.`,
    ourVisionTitle: "رؤيتنا",
    ourVisionDescription: "أن نكون روادًا في صناعة التموين وإدارة المرافق في المملكة العربية السعودية من خلال تقديم خدمات عالية الجودة، مبتكرة ومستدامة.",
    ourVisionPoints: [
      "تدقيق ذاتي صارم",
      "إجراءات تصحيحية",
      "تقييمات خارجية",
      "الالتزام الصارم بنظام إدارة الجودة الموّثق",
    ],
    ourVision2030: "تماشيًا مع رؤية 2030، نساهم بنشاط في تحسين جودة الحياة، وتعزيز التنويع الاقتصادي، وتطوير المواهب المحلية.",
      coreValuesTitle: "القيم الأساسية",
    coreValuesIntro: "هي في صميم كل ما نقوم به. نسعى لتقديم خدمة شخصية، والحفاظ على تواصل مفتوح، وضمان جودة عالية في العمل، والالتزام بالمواعيد، وتحسين خدماتنا باستمرار. من خلال الاستماع إلى ملاحظات عملائنا وتكييف خدماتنا مع احتياجاتهم الخاصة، بنينا علاقات قوية وسمعة ممتازة في الصناعة.",
    coreValues: [
      {
        title: "الاستدامة",
        description: "نولي الأولوية للممارسات المستدامة في جميع عملياتنا.",
      },
      {
        title: "التفاعل المجتمعي",
        description: "نشارك بفاعلية مع مجتمعاتنا ونساهم بشكل إيجابي.",
      },
      {
        title: "المرونة والتعاون",
        description: "نتكيف مع التغيير ونتعاون عن كثب مع العملاء وأصحاب المصلحة.",
      },
      {
        title: "رضا العملاء",
        description: "نقدم خدمات مخصصة، ونحافظ على تواصل مفتوح، ونتأكد من جودة العمل.",
      },
    ],
        servicesTitle: "خدماتنا",
    servicesDescription: "نقدم مجموعة واسعة من الخدمات عالية الجودة المخصصة للبيئات الصناعية والشركاتية والنائية.",
    servicesData: [
      {
        title: "تموين صناعي",
        description: "نوفر وجبات عالية الجودة ومغذية للفرق في المواقع المعزولة والتحديات، مع ضمان التوصيل الموثوق، وترتيبات مطبخ مخصصة، ولوجستيات فعالة.",
        items: ["حلول التموين", "خدمات الغسيل", "التنظيف", "تجهيز كابينة الميناء"],
      },
      {
        title: "التموين في المواقع البحرية والبرية",
        description: "نتخصص في تقديم خدمات تموين استثنائية للمنشآت البحرية والبرية، مع تجهيز للتعامل مع البيئات النائية والصناعية وضمان جودة عالية.",
        items: ["إقامة كبار وصغار الموظفين", "تصميم وتجهيز المطابخ / المطاعم"],
      },
      {
        title: "تموين الشركات (داخلي / خارجي)",
        description: "حلول تموين مخصصة لكافيتريات الشركات، الوجبات على المكتب، البوفيهات، وعربات الوجبات الخفيفة، لتقليل التوتر وزيادة إنتاجية الموظفين.",
        items: ["استقبال الشركات", "عشاء الشركات", "بوفيهات الشركات", "بوفيهات المؤتمرات"],
      },
      {
        title: "الفعاليات الخاصة (داخلي / خارجي)",
        description: "تجربة طعام راقية، مع قوائم ذات موضوعات، محطات طهي مباشرة، وترتيبات مخصصة.",
        items: ["الطعام الفاخر", "عشاء منزلي", "حفلات الزفاف", "نزهات / شواء"],
      },
      {
        title: "إنشاء وإدارة المخيمات",
        description: "تقدم البحر الأزرق للتموين مخيمات جاهزة ودائمة مصممة حسب احتياجات مشروعك.",
        items: ["التنظيف، الصيانة، الترفيه، الغسيل، الأمن، العيادة، النقل", "دعم تشغيلي 12/24 ساعة"],
      },
      {
        title: "التموين في الصحاري والمناطق النائية",
        description: "خدمات شاملة للطعام، الإقامة، والدعم للمناطق المعزولة في جميع أنحاء المملكة العربية السعودية.",
        items: [],
      },
      {
        title: "تجارة المواد الغذائية",
        description: "مزود موثوق للمواد الغذائية عالية الجودة، يتم التوريد محليًا وعالميًا، مع ضمان المنتجات الطازجة والآمنة وعالية الجودة.",
        items: [],
      },
    ],
      whyWeStandOutTitle: "لماذا نحن متميزون؟",
    whyWeStandOutDescription: "التزامنا بالتميز والابتكار يميزنا في صناعة التموين.",
    whyWeStandOutFeatures: [
      { title: "المأكولات المميزة", description: "قوائم مخصصة تعرض أفضل المأكولات العالمية والإقليمية." },
      { title: "التحضير في الموقع", description: "تموين شخصي مع وجبات طازجة معدة في موقعك." },
      { title: "تموين ذو طابع خاص", description: "خدمات التموين مصممة لتتناسب تمامًا مع فعاليات الشركات أو الفعاليات الخاصة." },
      { title: "توصيل سريع وموثوق", description: "متاح على مدار الساعة لتوصيل في الوقت المناسب مع أسطول كبير لتلبية الاحتياجات العاجلة والمستمرة." },
      { title: "مراقبة الجودة", description: "التميز المستمر من المصدر حتى التوصيل." },
      { title: "إدارة النفايات", description: "فصل، جمع، والتخلص المسؤول من النفايات." },
    ],
  
      healthSafetyTitle: "الالتزام بالصحة والسلامة",
    healthSafetyDescription: "نلتزم بالحفاظ على أعلى معايير الصحة والسلامة في جميع عملياتنا.",
    healthSafetyPoints: [
      { title: "سلامة الغذاء", description: "التعامل، التخزين، والتحضير بشكل صحيح لمنع التلوث." },
      { title: "ممارسات النظافة", description: "غسل اليدين، استخدام معدات الوقاية الشخصية، والحفاظ على بيئة عمل نظيفة." },
      { title: "تقييم الموردين", description: "ضمان أن المكونات تلبي معايير السلامة والجودة." },
      { title: "مراقبة درجة الحرارة", description: "الحفاظ عليها أثناء التحضير، التخزين، والنقل." },
      { title: "تدقيقات منتظمة", description: "التحقق المستمر لضمان الامتثال والتحسين." },
      { title: "التدريب والشهادات", description: "تدريب الفريق باستمرار على سلامة الغذاء والنظافة." },
      { title: "إجراءات الطوارئ", description: "بروتوكولات واضحة لمعالجة مسائل الصحة والسلامة." },
    ],
      projectsTitle: "المشاريع",
    completedProjectsTitle: "المشاريع المكتملة",
    runningProjectsTitle: "المشاريع الجارية",
    completedProjects: [
      "شركة أسيل يونيفرسال للملابس - الأردن",
      "AMC-AZDA JV تموين. الدمام-السعودية",
      "Metro VFR Limited - دبي",
      "Salini Construttori - دبي",
      "Todini Costruzioni Generali - دبي",
      "Belleli Energy Sr. دبي - الشارقة",
      "نادي دبي للبولو - دبي",
      "Dubai Precast - دبي",
      "Sendan Al Emarat - دبي",
      "منطقة المطار الحرة بالشارقة",
      "Sungwon Corporation - دبي",
      "Arabtec Construction LLC - دبي",
      "Bhawan Engineering. L.L.C. دبي",
      "Kele Contracting Co. LLC-دبي",
      "Dutco Beaty Balfour, دبي",
      "Meydan Racecourse, دبي",
      "Transgulf دبي، الإمارات والسعودية",
      "Al Laith Scaffolding LLC",
      "Green Works LLC, دبي",
      "Deco Emirates, دبي",
    ],
    runningProjects: [
      "Elegancia MEP - مشروع البحر الأحمر",
      "Fast Construction - مشروع البحر الأحمر",
      "First Fix - مشروع البحر الأحمر",
      "Elegancia Fit out",
      "Elenco Group",
      "Bk Gulf - مشروع البحر الأحمر",
      "Al Futtaim Engineering KSA"
    ],
     partnersTitle: "شركاؤنا في النجاح",
    partnersDescription: "شركاء موثوقون ساهموا في نموّنا ونجاحنا عبر مشاريع وصناعات متعددة.",
      contactTitle: "تواصل معنا",
    phone: "0559361915",
    email: "Info@mcatering.com",
    address: "48321، شارع عمر بن عبد العزيز، أملج، المملكة العربية السعودية",
    ctaTitle: "هل أنت جاهز؟",
    ctaDescription: "نحن مستعدون لإنشاء حل تموين وإعاشة مثالي لك!",
    qrText: "امسح لتواصل معنا",
    companyName: "البحر الأزرق للتموين والإعاشة",
    rights: "جميع الحقوق محفوظة.",
  }
  
};
